version: '3'
services:
  web:
    build: ./web
    ports:
      - "5000:5000"
    volumes:
      - ./web:/app
    tty: true
    environment:
      FLASK_ENV: development
#      FLASK_ENV: production
      TZ: Asia/Tokyo
  db:
    build: "./db"
    volumes:
      - ./db/sqls:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: tmppw
